export const PUBLIC_JOURNEY_REVALIDATE_SECONDS = 300;
export const PUBLIC_GUIDE_REVALIDATE_SECONDS = 3600;
export const PUBLIC_USER_REVALIDATE_SECONDS = 14400;
export const PUBLIC_PHOTO_REVALIDATE_SECONDS = 14400;
